In [37]:
import pandas as pd
import numpy as np


file_path = 'WineQT.csv'  
data = pd.read_csv(file_path)
data.describe().transpose()[["min","max"]]

                          min         max
fixed acidity         4.60000    15.90000
volatile acidity      0.12000     1.58000
citric acid           0.00000     1.00000
residual sugar        0.90000    15.50000
chlorides             0.01200     0.61100
free sulfur dioxide   1.00000    68.00000
total sulfur dioxide  6.00000   289.00000
density               0.99007     1.00369
pH                    2.74000     4.01000
sulphates             0.33000     2.00000
alcohol               8.40000    14.90000
quality               3.00000     8.00000
Id                    0.00000  1597.00000

In [41]:

data['quality'] = np.where(data['quality'] > 6, 1, 0)

columns_to_normalize = ['fixed acidity', 'volatile acidity', 'citric acid', 
                         'residual sugar', 'chlorides', 'free sulfur dioxide', 
                         'total sulfur dioxide', 'density', 'pH', 'sulphates', 
                         'alcohol']

# Manually normalize each column
for column in columns_to_normalize:
    # Calculating min and max
    min_val = data[column].min()
    max_val = data[column].max()
    
    # Applying min-max normalization 
    data[column] = (data[column] - min_val) / (max_val - min_val)

#to save the changes in csv file
transformed_file_path = 'WineQT_Modified.csv'  
data.to_csv(transformed_file_path, index=False)

In [23]:
data.describe().transpose()[["min","max"]]

                      min     max
fixed acidity         0.0     1.0
volatile acidity      0.0     1.0
citric acid           0.0     1.0
residual sugar        0.0     1.0
chlorides             0.0     1.0
free sulfur dioxide   0.0     1.0
total sulfur dioxide  0.0     1.0
density               0.0     1.0
pH                    0.0     1.0
sulphates             0.0     1.0
alcohol               0.0     1.0
quality               0.0     1.0
Id                    0.0  1597.0